name: Android CI
on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 12

      - name: Unit Test
        run: ./gradlew test

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
      
      - name: Upload Test Reports Folder
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: reports
          path: app/build/test-results